baseurl = "https://www.frogren.se/"
title = "Joakim Frögren"
author = "Joakim Frögren"
canonifyurls = true
enableEmoji = true
languagecode = "sv_se"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Joakim Frögren"
  description = "Ramblings of Ryan Frazier: Programmer, Musician, and Educator"
  github = "pianomanfrazier"
  linkedin = "pianomanfrazier"
  twitter = "pianomanfrazier"


[[menu.main]]
    name = "Om"
    url  = "https://frogren.se/om-mig/"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/jfrogren"
[[menu.main]]
    name = "Lösa anteckningar"
    url  = "https://frogren.se/losa-anteckningar/"
