baseurl = "https://www.frogren.se/"
title = "Joakim Frögren"
author = "Joakim Frögren"
canonifyurls = true
languagecode = "sv"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Joakim Frögren"
  disableWebFonts = false

[[menu.main]]
    name = "Om"
    url  = "https://frogren.se/om-mig/"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/jfrogren"
[[menu.main]]
    name = "Lösa anteckningar"
    url  = "https://frogren.se/losa-anteckningar/"
