baseurl = "https://www.frogren.se/"
title = "Joakim Frögren"
author = "Joakim Frögren"
canonifyurls = true
enableEmoji = true
theme = "black-and-light"
pygmentsstyle       = "bw"
pygmentscodefences  = true
languageCode = "sv"
defaultContentLanguage = "sv"


[params]
  sitename = "Joakim Frögren"
  dateform = "January 2, 2006"

[[menu.main]]
    name = "Om"
    url  = "/om-mig"

[[menu.main]]
    name = "Lösa anteckningar"
    url  = "/losa-anteckningar"

[[menu.main]]
  name = "Taggar"
  url  = "/tags"
