baseurl = "https://www.frogren.se/"
title = "Joakim Frögrens hemsida"
author = "Joakim Frögren"
canonifyurls = true
languagecode = "sv"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Joakim Frögren"
  disableWebFonts = false

[[params.navlinks]]
    name = "Om"
    url  = "om-mig/"
[[params.navlinks]]
    name = "Mikroblogg"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[params.navlinks]]
    name = "Bilder"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
