baseurl = "https://www.frogren2.se/"
title = "Joakim Frögren"
author = "Joakim Frögren"
canonifyurls = true
enableEmoji = true
theme = "black-and-light"
pygmentsstyle       = "bw"
pygmentscodefences  = true
languageCode = "sv"
defaultContentLanguage = "sv"

[frontmatter]
	date = [":filename", ":default", ":fileModTime"]

[permalinks]
  posts = '/:2006/:01/:title'

[params]
  sitename = "Joakim Frögren"
  dateform = "2006-01-02"

[[menu.main]]
    name = "Om"
    url  = "/om-mig"

[[menu.main]]
    name = "Lösa anteckningar"
    url  = "/losa-anteckningar"

[[menu.main]]
  name = "Taggar"
  url  = "/tags"

[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.youtube]
    disable = true
