baseurl = "https://frogren.se/"
languageCode = "sv"
defaultContentLanguage = "sv"

[taxonomies]
  kategorier = "kategorier"
  taggar = "taggar"

[permalinks]
  kategorier = "/kategorier/:slug/"
  taggar = "/taggar/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[paginate]
  default = 25

[params]
  showSummary = true

[languages]
  [languages.sv]
    languageName = "Svenska"
    weight = 1
    contentDir = "content"
    [languages.sv.taxonomies]
      kategorier = "kategorier"
      taggar = "taggar"

# Sitemap, rss, author och övriga generella inställningar kan läggas till efter behov.

