# MetaDataFormat = "toml"
baseurl = "https://frogren.se"
title = "Joakim Frögren"
# titleCaseStyle = "none" 
images = ["android-chrome-512x512.png", "android-chrome-192x192.png", "apple-touch-icon.png", "favicon-16x16.png", "favicon-32x32.png", "favicon.ico", "mstile-150x150.png", "safari-pinned-tab.svg"]
keywords = ["blogg", "hemsida", "sajt"]
pluralizelisttitles = false
CanonifyUrls = true
rssLimit = 20
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "sv"

enableRobotsTXT = true
enableEmoji = false
theme = ["hugo-video", "even"]

defaultContentLanguage = "sv"

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = false     # has chinese/japanese/korean ?
paginate = 25

[markup.goldmark.renderer]
unsafe = true

[author]                  # essential
  name = "Joakim Frögren"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[services.rss]
  limit = 20

[taxonomies]
  category = "kategorier"
  tag = "tags"

[permalinks]
  blogg = "/:slug/"

[[menu.main]]
  name = "Alla blogginlägg"
  url = "/blogg"
  weight = 1.0

[[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 2.0

[params]
  showSummary = true        # Tvingar Even-tematet att respektera brytpunkter för sammanfattningar
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com
  since = "2014"            # Site creation time
  title = "Joakim Frögren"
  images = ["images/joakim.png"]
  description = "En plats där jag reflekterar kring sånt som gör intryck och avtryck. Främst som ett sätt att själv minnas, men också med förhoppningen om att inspirera andra."
  keywords = ["blogg", "hemsida", "sajt"] # site info (optional)

  # Tvingar Google Fonts att leverera den utökade europeiska teckenuppsättningen
  googleFontsSubsets = ["latin", "latin-ext"]

  # paginate of archives, tags and categories
  # general archives
  archivePaginate = 25
  # blog archive. This indexes n /posts/ not n /years/ for pagination purposes
  blogPaginate = 200

  # show 'xx Posts In Total' in archive page ?
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Syntax highlighting by highlight.js
  highlightInClient = false

  #  archetypes/default.md
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            #
  autoCollapseToc = false   # Auto expand and collapse toc                              #
  fancybox = true           # see https://github.com                 #

  # mathjax
  mathjax = false           # see https://mathjax.org                              #
  mathjaxEnableSingleDollar = false                                                     #
  mathjaxEnableAutoNumber = false                                                       #
  mathjaxUseLocalFiles = false  # You should install mathjax in `your-site/static/lib/mathjax`

  postMetaInFooter = false   # contain author, lastMod, markdown link, license           #
  linkToMarkDown = false    # Only effective when hugo will output .md files.           #
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org" target="_blank">CC BY-NC-ND 4.0</a>'

  baiduPush = false        # baidu push                  # 百度

    # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['bigfoot-default.css','codeblock.css','mine.css', 'dark.css']
  customJS = ['codeblock.js']

  uglyURLs = false          # please keep same with uglyurls setting

  [params.publicCDN]        # load these files from public cdn                          #
    enable = false
  #  jquery = '<script src="https://jsdelivr.net"></script>'slideout = '<script src="https://jsdelivr.net" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
  #  fancyboxJS = '<script src="https://jsdelivr.gh"></script>'
  #  fancyboxCSS = '<link rel="stylesheet" href="https://jsdelivr.net" />'
  #  timeagoJS = '<script src="https://jsdelivr.net" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
  #  timeagoLocalesJS = '<script src="https://jsdelivr.net" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
  #  flowchartDiagramsJS = '<script src="https://jsdelivr.net" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://jsdelivr.net" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
  #  sequenceDiagramsCSS = '<link rel="stylesheet" href="https://jsdelivr.net" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
  #  sequenceDiagramsJS = '<script src="https://jsdelivr.net" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://jsdelivr.net" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://jsdelivr.net" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://jsdelivr.net" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

# See https://gohugo.io
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

[outputFormats]
    [outputFormats.RSS]
        baseName = "index"

[outputs]
 home = ["HTML", "RSS"]
 page = ["HTML"]
 section = ["HTML", "RSS"]
 taxonomy = ["HTML", "RSS"]
 term = ["HTML", "RSS"]

[security]
  allowContent = ['.*']
